### ISSUE TITLE
Make Year part of Holiday

### ISSUE THREAD

**Issue by agustintorres** [rickar/cal#10]
I would like to specify my own custom holidays for a calendar based on an exact match of day, month, and year. Currently I cannot do this. Can we make this a valid Holiday definition:

- Month, Day, and Year

If this sounds good to you I could even make a PR for it since it should be a very simple change. All that needs to change is the Holiday struct and the matches() function.

**Comment by rickar** [comment]
Sure, feel free to send a PR.

**Comment by agustintorres** [comment]
Here: https://github.com/rickar/cal/pull/11
