### ISSUE TITLE
ChristmasDay / New Years missing Observed?

### ISSUE THREAD

**Issue by 0x-2a** [rickar/cal#121]
Shouldn't [ChristmasDay](https://github.com/rickar/cal/blob/master/v2/aa/aa_holidays.go#L126) have the `Observed: weekendAlt` attribute? 

And New Years should probably have Sat/Sun -> Mon 
```
NewYear = &Holiday{
    Name:     "New Year's Day",
    Month:    time.January,
    Day:      1,
    Func:     CalcDayOfMonth,
    Observed: []AltDay{
        {Day: time.Saturday, Offset: 2},
        {Day: time.Sunday, Offset: 1},
    },
}
```

Sources:
Christmas: https://www.nyse.com/publicdocs/ICE_NYSE_2022_Yearly_Trading_Calendar.pdf
New Years: https://www.nasdaq.com/articles/2020-stock-market-holidays-and-bond-market-holidays-2019-12-28

**Comment by rickar** [comment]
You must be looking at the aa version? Different countries have different rules. The us version for example does use weekendAlt.
