### ISSUE TITLE
Mexico (MX) Holidays

### ISSUE THREAD

**Issue by torabisu** [rickar/cal#122]
I noticed that Mexico holidays has not been implemented.  Is this already on the roadmap?  If not, can it be added?  I can assist / contribute if necessary

**Comment by torabisu** [comment]
I contributed and created a [pull request](https://github.com/rickar/cal/pull/125), so going to close this issue

**Comment by rickar** [comment]
> I noticed that Mexico holidays has not been implemented. Is this already on the roadmap? If not, can it be added? I can assist / contribute if necessary

Thanks! There's not really a roadmap. I was hoping for people living in or familiar with the additional countries to contribute the holidays that people actually care about. Hard for me to know from Wikipedia or whatever site sometimes.
