### ISSUE TITLE
#IsWeekdayN broken

### ISSUE THREAD

**Issue by johnmcconnell** [rickar/cal#2]
https://github.com/rickar/cal/blob/master/cal.go#L22
Does not work for Memorial Day for example. Fixed in #1

**Comment by rickar** [comment]
What do you mean by "does not work"? There's already a test for Memorial Day in cal_test.go which passes:

{time.Date(2014, 5, 26, 12, 0, 0, 0, time.UTC), true},
{time.Date(2014, 5, 25, 12, 0, 0, 0, time.UTC), false},
{time.Date(2014, 5, 27, 12, 0, 0, 0, time.UTC), false},

**Comment by johnmcconnell** [comment]
Hmm... I don't remember. I just ran it with 2015, 5, 25 and it past. I was not expecting it to.
