### ISSUE TITLE
Holiday per country

### ISSUE THREAD

**Issue by jhayotte** [rickar/cal#27]
Hi!

First of all, I want to tell that your library is awesome!

I need `CountWorkdays` with the notion of country.

So I am going to do a PR with a proposal where the struct Holiday is enriched.

```golang
type Holiday struct {
	Month   time.Month
	Weekday time.Weekday
	Day     int
	Offset  int
	Year    int
	Country string // i.e FR-fr
	Func    HolidayFn

	// last values used to calculate month and day with Func
	lastYear int
	lastLoc  *time.Location
}
```

Do you have something in mind regarding such feature? From my point of view, the current implementation of IsHoliday works only for a single country.

Cheers,

**Comment by jhayotte** [comment]
I added a PR #28

**Comment by rickar** [comment]
Thanks! I'm not sure I understand the use case for this though. I would normally expect to create a map from string to calendar instances and use that to pick the correct calendar to use. By adding a country field to the struct I would think you would have to create copies of all the methods that accept a country to match on which would make things a lot more messy. Is there a reason that a map wouldn't work?

**Comment by jhayotte** [comment]
A bit of context to describe my use case. 
The current solution gathers the holidays in the same bucket and we cannot detect that the 8th of May is a labor day in Spain but not in France.
I have a Slice of entities located in several countries and I need to have a relevant CountWorkDays for each of them.
To be future proof and allow people to filter CountWorkDays on a specific range of Countries then a map might make more sense.
If you agree with that, I will apply the change to have a map of Country in Calendar.

**Comment by rickar** [comment]
Sure, feel free to send a PR for that if you want.
