### ISSUE TITLE
IsWorkTime possibly incorrect for workdays that overlap midnight?

### ISSUE THREAD

**Issue by guycall** [rickar/cal#49]
I am trying to implement DeductWorkHours and PreviousWorkdayEnd. Things get a little complex when dealing with workdays that overlap midnight. This lead me to wonder if the current implementation of IsWorkTime works as expected?

I added some tests in my fork to TestIsWorkTime https://github.com/progress-tech/cal/blob/deductworkhours/v2/cal_business_test.go#L128-L133 

```
cal3 := NewBusinessCalendar()
cal3.SetWorkHours(22*time.Hour, 6*time.Hour)

{cal3, dt(2020, 4, 5, 21, 00), false},  // Sunday
{cal3, dt(2020, 4, 5, 23, 00), false},  // Sunday
{cal3, dt(2020, 4, 6, 02, 00), true},   // Monday
{cal3, dt(2020, 4, 10, 21, 00), false}, // Friday
{cal3, dt(2020, 4, 10, 23, 00), true},  // Friday
{cal3, dt(2020, 4, 11, 02, 00), false}, // Saturday
```

The workday that starts 22:00 on a Friday, pauses at midnight and then reconvenes at the start of Monday. I guess this would not be the common interpretation of a workday that starts at 10pm and finishes at 4am. 

It is of course open to interpretation, but I would imagine a workday that starts at Friday 10pm and then ends 4am Saturday would be closer to common expectations. 

Do you have any thoughts? Would you be open to a PR that makes such a change to IsWorkTime? I guess the problem is this would be a breaking change.

**Comment by rickar** [comment]
Nice catch. I agree with your interpretation and it makes sense to fix. I'm not worried about it being a breaking change at this time because it's still in beta so these types of things can get worked out. Feel free to send your PR. Thanks!

**Comment by guycall** [comment]
Great, and are you open to the addition of DeductWorkHours and PreviousWorkdayEnd?

**Comment by rickar** [comment]
Yeah, sounds good to me. Though it should probably be SubWorkHours to follow the convention established by Time.Add() and Time.Sub().
