### ISSUE TITLE
Adding Custom Non-Working date

### ISSUE THREAD

**Issue by BuLEEto** [rickar/cal#54]
Hi, I don't seem to be able to get any custom non-working dates working correctly.

This is the summary of what I'm trying to achieve:

```
var ukCalandar = cal.NewBusinessCalendar()

ukCalandar.Name = "Internal Cal"
ukCalandar.Description = "All UK Bank Holidays"

nonworkingdays := []cal.Holiday{
	{
		Day:   23,
		Month: time.December,
	},
	{
		Day:   24,
		Month: time.December,
	},
	{
		Day:   29,
		Month: time.December,
	},
	{
		Day:   30,
		Month: time.December,
	},
	{
		Day:   31,
		Month: time.December,
	},
}

ukCalandar.AddHoliday(
	gb.BoxingDay,
	gb.ChristmasDay,
	gb.EarlyMay,
	gb.EasterMonday,
	gb.GoodFriday,
        gb.NewYear,
	gb.SpringHoliday,
	gb.SummerHoliday,
)

for a := range nonworkingdays {
	ukCalandar.AddHoliday(&nonworkingdays[a])
}

```

When I look at ukCalandar.WorkdaysInRange(time.Now(), endofmonth) I get 15 days back, or 14 days if I look at ukCalandar.WorkdaysRemain(time.Now())

It seems that the custom nonworkingdays are not being included?

Thanks for the advice/help in advance.

**Comment by BuLEEto** [comment]
Ah I figured it out! Need to use

`Func:      cal.CalcDayOfMonth`

**Comment by jslq** [comment]
Hey,can you type it how to use cal.CalcDayOfMonth, I cant figured it out!

**Comment by rickar** [comment]
The `Func` field on `Holiday` is required. So you can't have:

```
customHoliday := &cal.Holiday{
    Month: time.July,
    Day: 15,
}
```

You have to use `CalcDayOfMonth` to indicate which type of calculation to use.

```
customHoliday := &cal.Holiday{
    Month: time.July,
    Day: 15,
    Func: cal.CalcDayOfMonth,
}
```
