### ISSUE TITLE
Can V2 already be used in production?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [rickar/cal#60]
Hi @rickar,
I was checking the latest release that are 'pre-release' but there is no specific mention of being beta on the README.
I was wondering if the last pre-release is stable enough to be used in production.

Thank you very much.

**Comment by rickar** [comment]
Yes, the only reason it's still in beta is in case we needed to make any potentially breaking changes in API and issue #49. I was planning to move it out of beta status soon.
