### ISSUE TITLE
Set a date as a workday

### ISSUE THREAD

**Issue by h17liner** [rickar/cal#61]
Hello, 
Amazing package! 
But i have some (mb stupid) question: Is it possible to mark a date as a workday ?

**Comment by rickar** [comment]
Thanks! There are multiple options to accomplish this depending on how often that extra workday occurs:

- Use BusinessCalendar.SetWorkday if you want to change a day globally.
- Use BusinessCalendar.SetWorkday to set a global work day and then add a custom Holiday to exclude non-working occurrences of that day.
- Create a custom function for BusinessCalendar.WorkdayFunc where you can implement your own logic to return specific extra work days.
