### ISSUE TITLE
setting a repeating holiday marks the day before as not workday

### ISSUE THREAD

**Issue by martinlindenberg** [rickar/cal#64]
Hi 
i am adding the first of May as a holiday to an empty calendar.
After doing that, the isWorkday flag of the day before changes:

https://play.golang.org/p/yZcCw0p8bWL

Am i doing something wrong or is this a bug in V1?

![image](https://user-images.githubusercontent.com/14071524/115695697-4e41f500-a362-11eb-862a-19d45752c8f6.png)

**Comment by martinlindenberg** [comment]
I tried out with a couple of dates it seems to be related to having a holiday on a Saturday. The Friday before is suddenly marked as non working day.

**Comment by martinlindenberg** [comment]
just discovered that there is also a v2
issue is not present there. 

probably a good time to migrate to v2 :)
https://play.golang.org/p/71qknZqASle

**Comment by rickar** [comment]
Yes, the default behavior on v1 was to observe holidays that fall on weekends on the nearest weekday. I thought that was common enough to be the default but have since learned my lesson. 😉

**Comment by asaleem772** [comment]
> Yes, the default behavior on v1 was to observe holidays that fall on weekends on the nearest weekday. I thought that was common enough to be the default but have since learned my lesson. 😉

this can be controlled, if you set observed as `observedExact`.

**Comment by martinlindenberg** [comment]
thanks @asaleem772 

this comment was really helpful, since i haven't yet started working on upgrading to v2. 
using observedExact now as a hotfix
