### ISSUE TITLE
Bug with NewYear (maybe others too?)

### ISSUE THREAD

**Issue by DenisRichartz** [rickar/cal#7]
I think i found a bug concerning the NewYear Holiday (possibly others holidays affected).

```
	c := cal.NewCalendar()

	//c.AddHoliday(cal.NewYear)
	t := time.Date(2017, 1, 2, 12, 40, 0, 0, time.UTC)

	if c.IsWorkday(t) {
		fmt.Println("Is Workday")
	}

	fmt.Println(c.Workdays(2017, t.Month()))
```
Gives me:

Is Workday
22

After uncommenting the NewYear Holiday:

21

NewYear is on the  January 1st, but adding the NewYear Holiday affects January 2nd. So the 2nd is neither Workday nor Holiday. Is this intended behaviour?

€: Okay, after doing a little research this seems to be based on the fact that NewYear is "observed" in the States. Germany does not do this, if Holidays happen on a Sunday they are in fact not moved to another workday. 
```
    c.Observed = cal.ObservedExact
```
Solves this problem. 

I suggest adding a small note to the readme about this behaviour.

**Comment by rickar** [comment]
Thanks for the suggestion. I will add that.
