### ISSUE TITLE
`IsHoliday` skips holidays where `Func` returns a different month

### ISSUE THREAD

**Issue by danielwhite** [rickar/cal#81]
https://github.com/rickar/cal/blame/master/v2/cal.go#L55-L57 has introduced a regression for holidays that have exceptions on the month they apply.

In the following example with "Friday before the AFL Grand Final", the year 2020 moves the holiday to October instead of the usual September occurrence.

```go
package main

import (
	"fmt"
	"time"

	"github.com/rickar/cal/v2"
	"github.com/rickar/cal/v2/au"
)

func main() {
	// Exceptional case 23/10/2020 (usually September).
	//
	// See: https://github.com/rickar/cal/blob/a2ee0b32e8e00ec8eba013bc2df98cf74364b30a/v2/au/au_holidays.go#L363-L372
	d := time.Date(2020, 10, 23, 0, 0, 0, 0, time.UTC)

	// With the calendar, the holiday is skipped.
	//
	// See: https://github.com/rickar/cal/blob/a2ee0b32e8e00ec8eba013bc2df98cf74364b30a/v2/cal.go#L55-L57

	c := cal.NewBusinessCalendar()
	c.AddHoliday(au.HolidaysVIC...)
	actual, observed, _ := c.IsHoliday(d)
	fmt.Printf("calendar: actual=%t observed=%t\n", actual, observed)

	// With the holiday, the actual and observed times match the date.

	actualT, observedT := au.FridayBeforeAflFinal.Calc(d.Year())
	actual, observed = actualT.Equal(d), observedT.Equal(d)
	fmt.Printf("holiday: actual=%v observed=%v\n", actual, observed)
}
```

https://play.golang.org/p/VmoJX_VNjRA

I'd considered a naive solution to this case similar to Easter such that the "Month" isn't defined on the "Holiday".

But my bigger concern is that this is more widespread in other holidays and acts as a footgun since the holiday tests aren't really arranged to exercise this aspect of calculating the holidays.

Happy to raise a PR if you've got some suggestions.

**Comment by rickar** [comment]
Thanks for this. I thought having tests for all holidays would cover it but forgot that the holiday calcs were being tested directly instead of through a Calendar. I ended up changing to add an optional internal cache to handle this more generically.

**Comment by danielwhite** [comment]
Thanks a lot. Much better than anything I'd considered. 👍
