### ISSUE TITLE
Some holidays reported with an invalid date

### ISSUE THREAD

**Issue by WrathOfZombies** [rickar/cal#83]
**Issue:**
We have a requirement where we need to report all the available holidays in a given country. To meet that requirement we have taken a simplistic approach as follows, to loop over all the registered holidays in a region and `calc` the actual and observed dates and return them to the caller.

```go
for _, holiday := range holidays {
    actual, observed := cal.holidays.Calc(regionalYear)
    // do something here with the date
}
```

The issue is that when doing this, some Holidays are calculated incorrectly and repeatedly across multiple years. For example, when checking Ukraine Holidays for the years 2021 or 2022, and using the psuedocode above, we get:

```js
actual: "2021-05-01T00:00:00Z"
name: "День праці"
observed: "2021-05-03T00:00:00Z"

actual: "0001-01-01T00:00:00Z"
name: "День праці"
observed: "0001-01-01T00:00:00Z"
```

The first entry is the correctly registered "International Workers Day", where as the second is the same but without a date or month component. Investigation shows that this is indeed how the metadata is structured here  https://github.com/rickar/cal/blob/90b7ddf4cc5759325f4dc023193c808f83a8ce3f/v2/ua/ua_holidays.go#L55 with only one of the entires having a proper Day & Month.

Just want to understand what's the reason behind this and what's the recommended approach to deal with this issue. I can also simply ignore holidays with no Day & Month component but I wasn't sure if that's the right solution here. Please advise.

**Repro steps:**
1. Use the above pseudo code to run through Ukraine's holidays
2. For each holiday Calc the actual and observed dates
3. Print them out

**Expected:**
Only one valid entry for "International Workers Day" should be reported

**Actual:**
Two entries are reported, out of which one of them is wrong.

Library version: 
Golang version: go1.17.1 darwin/amd64

**Comment by rickar** [comment]
I would guess that you are getting the result of LabourDay2 which has the same name but ended in 2017, so has no value for 2021 or 2022. In general, a zero time is returned if a Holiday doesn't apply for the given year. You can check it with t.IsZero().

**Comment by rickar** [comment]
Possibly. I thought it wasn't really an "error" for a holiday not to occur in a particular year so that's why I went with the zero value instead. It would be a breaking change to add the error return now.
