### ISSUE TITLE
New Years Day did not report as a Holiday

### ISSUE THREAD

**Issue by schmidty1913** [rickar/cal#84]
I was expecting New Years Day 1/1/2022 to report as an observed Holiday on 12/31/2021
It did not.

I tested for New Years Day 1/1/2023 and it reported as an observered Holiday on 12/31/2022

`calendar := cal.NewBusinessCalendar()
calendar.AddHoliday(
		us.NewYear
	)

dates := []time.Time{
		time.Date(2021, time.December, 31, 0, 0, 0, 0, cal.DefaultLoc),
		time.Date(2022, time.January, 1, 0, 0, 0, 0, cal.DefaultLoc),
		time.Date(2022, time.December, 31, 0, 0, 0, 0, cal.DefaultLoc),
		time.Date(2023, time.January, 1, 0, 0, 0, 0, cal.DefaultLoc),
	}

	for _, date := range dates {
		log.Infof("Test %v", date.Format("Mon Jan 2 15:04"))

		actual, observed, holiday := calendar.IsHoliday(date)
		log.Infof("Actual: %v Observed: %v Holiday %+v", actual, observed, holiday)

	}
	return
`
Output
time="2021-12-31T10:07:11-06:00" level=info msg="Test Fri Dec 31 2021 00:00"
time="2021-12-31T10:07:11-06:00" level=info msg="Actual: false Observed: false Holiday <nil>"
time="2021-12-31T10:07:11-06:00" level=info msg="Test Sat Jan 1 2022 00:00"
time="2021-12-31T10:07:11-06:00" level=info msg="Actual: true Observed: false Holiday &{Name:New Year's Day Description: Type:1 StartYear:0 EndYear:0 Except:[] Month:January Day:1 Weekday:Sunday Offset:0 CalcOffset:0 Julian:false Observed:[{Day:Saturday Offset:-1} {Day:Sunday Offset:1}] Func:0x48aa20}"
time="2021-12-31T10:07:11-06:00" level=info msg="Test Sat Dec 31 2022 00:00"
time="2021-12-31T10:07:11-06:00" level=info msg="Actual: false Observed: true Holiday &{Name:New Year's Day Description: Type:1 StartYear:0 EndYear:0 Except:[] Month:January Day:1 Weekday:Sunday Offset:0 CalcOffset:0 Julian:false Observed:[{Day:Saturday Offset:-1} {Day:Sunday Offset:1}] Func:0x48aa20}"
time="2021-12-31T10:07:11-06:00" level=info msg="Test Sun Jan 1 2023 00:00"
time="2021-12-31T10:07:11-06:00" level=info msg="Actual: true Observed: false Holiday &{Name:New Year's Day Description: Type:1 StartYear:0 EndYear:0 Except:[] Month:January Day:1 Weekday:Sunday Offset:0 CalcOffset:0 Julian:false Observed:[{Day:Saturday Offset:-1} {Day:Sunday Offset:1}] Func:0x48aa20}"

**Comment by rickar** [comment]
Thanks, I wasn't handling holidays that crossed year boundaries previously. It's weird to think that technically we observed New Year's Day twice in 2021.
