### ISSUE TITLE
Possible to add custom dates?

### ISSUE THREAD

**Issue by ZerkerEOD** [rickar/cal#86]
My firm is closed from Christmas to Newyears. Is there an example that you could give that would allow marking the days in between? Or a way to import a CSV of dates?

**Comment by rickar** [comment]
For that I would create a custom WorkdayFunc that returns false if the date is >= 25-Dec and <= 1-Jan. Alternatively since it's only a few days you could create ChristmasBreak1 - 6 custom Holidays for 26-Dec, 27-Dec, etc.
