### ISSUE TITLE
Special holidays such as Platinum Jubilee of Elizabeth II

### ISSUE THREAD

**Issue by WrathOfZombies** [rickar/cal#89]
In order to celebrate the Queen's Platinum Jubilee, some holidays in the UK region have changed for 2022. Specifically:

**May 30th Spring Bank** holiday has been moved to **2nd June**.
**3rd June** is a new bank holiday all together.

Thoughts on adding support for that? I'd be happy to send out a PR, once we have agreed on an approach to add these into the library.

Source: https://www.gov.uk/bank-holidays

**Comment by rickar** [comment]
Thanks for the notice. It was quick enough to implement so I went ahead and did it.
